# Generated by Django 2.1.7 on 2019-04-23 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('classroom_id', models.CharField(default='X0000', max_length=5, primary_key=True, serialize=False, unique=True, verbose_name='教室编号')),
                ('classroom_capacity', models.IntegerField(default=40, verbose_name='教室容量')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(default='XXXX00000', max_length=9, primary_key=True, serialize=False, unique=True, verbose_name='课程代码')),
                ('course_name', models.CharField(default='aCourse', max_length=50, unique=True, verbose_name='课程')),
                ('course_capacity', models.IntegerField(default=40, verbose_name='课程容量')),
                ('course_classroom_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FDUSystem.Classroom', verbose_name='上课教室')),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('major_id', models.CharField(default='XXXX0001', max_length=8, primary_key=True, serialize=False, unique=True, verbose_name='专业代码')),
                ('major_name', models.CharField(default='aMajor', max_length=50, verbose_name='专业')),
            ],
        ),
        migrations.CreateModel(
            name='PreCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cur_course_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cur_course_id', to='FDUSystem.Course', verbose_name='课程代码')),
                ('pre_course_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pre_course_id', to='FDUSystem.Course', verbose_name='先修课程代码')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('school_id', models.CharField(default='XXXX', max_length=4, primary_key=True, serialize=False, unique=True, verbose_name='学院代码')),
                ('school_name', models.CharField(default='aSchool', max_length=50, unique=True, verbose_name='学院')),
            ],
        ),
        migrations.CreateModel(
            name='SelectCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sc_score', models.IntegerField(default=60, verbose_name='成绩')),
                ('sc_course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FDUSystem.Course', verbose_name='课程代码')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('stu_id', models.CharField(default='00000000000', max_length=11, primary_key=True, serialize=False, unique=True, verbose_name='学号')),
                ('stu_name', models.CharField(default='aStudent', max_length=50, verbose_name='姓名')),
                ('stu_sex', models.CharField(choices=[('male', '男'), ('female', '女')], default='male', max_length=20, verbose_name='性别')),
                ('stu_age', models.IntegerField(default=20, verbose_name='年龄')),
                ('stu_major', models.ForeignKey(default='计算机科学与技术', on_delete=django.db.models.deletion.CASCADE, to='FDUSystem.Major', verbose_name='专业')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.CharField(default='00000', max_length=5, primary_key=True, serialize=False, unique=True, verbose_name='工号')),
                ('teacher_name', models.CharField(default='aTeacher', max_length=50, verbose_name='姓名')),
                ('teacher_sex', models.CharField(choices=[('male', '男'), ('female', '女')], default='male', max_length=20, verbose_name='性别')),
                ('teacher_age', models.IntegerField(default=40, verbose_name='年龄')),
                ('teacher_title', models.CharField(choices=[('Assistant', '助教'), ('Lecturer', '讲师'), ('Associate Professor', '副教授'), ('Professor', '教授')], default='Lecturer', max_length=20, verbose_name='职称')),
                ('teacher_salary', models.FloatField(default=8000.0, verbose_name='月薪')),
                ('teacher_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FDUSystem.School', verbose_name='就职学院')),
            ],
        ),
        migrations.CreateModel(
            name='UserExtension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_admin', models.CharField(max_length=11, null=True, unique=True, verbose_name='管理员工号')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extension', to=settings.AUTH_USER_MODEL)),
                ('user_student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FDUSystem.Student')),
                ('user_teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FDUSystem.Teacher')),
            ],
        ),
        migrations.AddField(
            model_name='selectcourse',
            name='sc_stu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FDUSystem.Student', verbose_name='学号'),
        ),
        migrations.AddField(
            model_name='major',
            name='major_school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FDUSystem.School', verbose_name='隶属'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FDUSystem.Teacher', verbose_name='授课教师（工号）'),
        ),
    ]
