# Generated by Django 2.1.7 on 2019-04-24 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FDUSystem', '0003_auto_20190425_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextension',
            name='user_student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FDUSystem.Student'),
        ),
        migrations.AlterField(
            model_name='userextension',
            name='user_teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FDUSystem.Teacher'),
        ),
    ]
