# Generated by Django 2.1.7 on 2019-04-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FDUSystem', '0004_auto_20190425_0320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userextension',
            name='user_admin',
        ),
        migrations.RemoveField(
            model_name='userextension',
            name='user_student',
        ),
        migrations.RemoveField(
            model_name='userextension',
            name='user_teacher',
        ),
        migrations.AddField(
            model_name='userextension',
            name='user_belong',
            field=models.CharField(choices=[('admin', 'admin'), ('student', 'student'), ('teacher', 'teacher')], default='admin', max_length=10),
        ),
        migrations.AddField(
            model_name='userextension',
            name='user_number',
            field=models.CharField(default='000000', max_length=11, unique=True, verbose_name='绑定信息'),
        ),
    ]
